export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const LOGOUT_USER = 'LOGOUT_USER'

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const CONFIRM_EMAIL_REQUEST = 'CONFIRM_EMAIL_REQUEST'
export const CONFIRM_EMAIL_SUCCESS = 'CONFIRM_EMAIL_SUCCESS'
export const CONFIRM_EMAIL_FAILURE = 'CONFIRM_EMAIL_FAILURE'

export const INITIATE_USER_EMAIL_CHANGE_REQUEST = 'INITIATE_USER_EMAIL_CHANGE_REQUEST'
export const INITIATE_USER_EMAIL_CHANGE_SUCCESS = 'INITIATE_USER_EMAIL_CHANGE_SUCCESS'
export const INITIATE_USER_EMAIL_CHANGE_FAILURE = 'INITIATE_USER_EMAIL_CHANGE_FAILURE'

export const CONTINUE_EMAIL_CHANGE_REQUEST = 'CONTINUE_EMAIL_CHANGE_REQUEST'
export const CONTINUE_EMAIL_CHANGE_SUCCESS = 'CONTINUE_EMAIL_CHANGE_SUCCESS'
export const CONTINUE_EMAIL_CHANGE_FAILURE = 'CONTINUE_EMAIL_CHANGE_FAILURE'

export const FINISH_EMAIL_CHANGE_REQUEST = 'FINISH_EMAIL_CHANGE_REQUEST'
export const FINISH_EMAIL_CHANGE_SUCCESS = 'FINISH_EMAIL_CHANGE_SUCCESS'
export const FINISH_EMAIL_CHANGE_FAILURE = 'FINISH_EMAIL_CHANGE_FAILURE'

export const SHOW_SUCCESS_RESPONSE_MESSAGE = 'SHOW_SUCCESS_RESPONSE_MESSAGE'
export const SHOW_FAILURE_RESPONSE_MESSAGE = 'SHOW_FAILURE_RESPONSE_MESSAGE'
export const HIDE_RESPONSE_MESSAGE = 'HIDE_RESPONSE_MESSAGE'

export const INITIATE_PASSWORD_RECOVERY_REQUEST = 'INITIATE_PASSWORD_RECOVERY_REQUEST'
export const INITIATE_PASSWORD_RECOVERY_SUCCESS = 'INITIATE_PASSWORD_RECOVERY_SUCCESS'
export const INITIATE_PASSWORD_RECOVERY_FAILURE = 'INITIATE_PASSWORD_RECOVERY_FAILURE'

export const FINISH_PASSWORD_RECOVERY_REQUEST = 'FINISH_PASSWORD_RECOVERY_REQUEST'
export const FINISH_PASSWORD_RECOVERY_SUCCESS = 'FINISH_PASSWORD_RECOVERY_SUCCESS'
export const FINISH_PASSWORD_RECOVERY_FAILURE = 'FINISH_PASSWORD_RECOVERY_FAILURE'

export const PASSWORD_CHANGE_REQUEST = 'PASSWORD_CHANGE_REQUEST'
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS'
export const PASSWORD_CHANGE_FAILURE = 'PASSWORD_CHANGE_FAILURE'
